name: Testing Triager on Closed issues
run-name: Triager Tester in GitHub Actions

on:

    issues:
        types: [closed]

jobs:
  issue_closed:
    name: Issue Closed
    runs-on: ubuntu-latest
    steps:
      - name: Commenting on the issue
        uses: actions/github-script@v4
        with:
          script: |
            const { data: issueData } = await github.issues.get({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const commentsUrl = issueData.comments_url;
            const { data: commentsData } = await github.request(commentsUrl);

            const sandboxIssueNumber = 10;
            const sandboxOwner = context.repo.owner;
            const sandboxRepo = context.repo.repo;

            resultString = "";

            // Filtering the Comments Data to find "FYI"
            for (const comment of commentsData) {
              console.log(comment);
              const lowercaseCommentBody = comment.body.toLowerCase();
              if (lowercaseCommentBody.includes("fyi")) {
                const restCommentBody = lowercaseCommentBody.body.replace("fyi", "");
                const profiles = restCommentBody.replace(/[^\w\s]/g, '');
                resultString += `Assigned developers: ${profiles}\n`;
              }
            }

            if (resultString.length === 0) {
              resultString += "No Assigned Developers :(";
            }

            await github.issues.createComment({
              issue_number: sandboxIssueNumber,
              owner: sandboxOwner,
              repo: sandboxRepo,
              body: resultString
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
